In [2]:
import pandas as pd
import numpy as np
import re

from pathlib import Path

In [3]:
DATA_PATH = "../data/raw/se-merchants-2026-04-15 (1).xlsx"

xls = pd.ExcelFile(DATA_PATH)

xls.sheet_names

['Blibli', 'GoFood', 'Shopee', 'Tokopedia', 'Semua Platform']

In [4]:
dfs = {
    sheet: pd.read_excel(DATA_PATH, sheet_name=sheet)
    for sheet in xls.sheet_names
}

In [5]:
for sheet, df in dfs.items():

    print("=" * 60)
    print(sheet)
    print("=" * 60)

    print("Shape:", df.shape)

    print("\nColumns:")
    print(df.columns.tolist())

    print("\nSample:")
    display(df.head(3))

============================================================
Blibli
============================================================
Shape: (4, 20)

Columns:
['platform', 'merchantName', 'merchantUrl', 'merchantId', 'address', 'provinceCode', 'provinceName', 'regencyCode', 'regencyName', 'districtCode', 'districtName', 'category', 'rating', 'totalProducts', 'totalSold', 'joinDate', 'isOfficialStore', 'phone', 'description', 'scrapedAt']

Sample:

,platform,merchantName,merchantUrl,merchantId,address,provinceCode,provinceName,regencyCode,regencyName,districtCode,districtName,category,rating,totalProducts,totalSold,joinDate,isOfficialStore,phone,description,scrapedAt
0,blibli,Apotek Adi Pharma,https://www.blibli.com/merchant/apotek-adi-pharma,apotek-adi-pharma,Kab. Padang Pariaman,1377,Pariaman,1306,PADANG PARIAMAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,2026-04-14T09:59:33.827Z
1,blibli,Apotek Al-Fath,https://www.blibli.com/merchant/apotek-al-fath,apotek-al-fath,Kab. Padang Pariaman,1377,Pariaman,1306,PADANG PARIAMAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,2026-04-14T09:59:33.827Z
2,blibli,Apotek Ara Medica,https://www.blibli.com/merchant/apotek-ara-medica,apotek-ara-medica,Kab. Padang Pariaman,1377,Pariaman,1306,PADANG PARIAMAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,2026-04-14T09:59:33.828Z

============================================================
GoFood
============================================================
Shape: (601, 20)

Columns:
['platform', 'merchantName', 'merchantUrl', 'merchantId', 'address', 'provinceCode', 'provinceName', 'regencyCode', 'regencyName', 'districtCode', 'districtName', 'category', 'rating', 'totalProducts', 'totalSold', 'joinDate', 'isOfficialStore', 'phone', 'description', 'scrapedAt']

Sample:

,platform,merchantName,merchantUrl,merchantId,address,provinceCode,provinceName,regencyCode,regencyName,districtCode,districtName,category,rating,totalProducts,totalSold,joinDate,isOfficialStore,phone,description,scrapedAt
0,gofood,"Risol Mayo Delicious, Lubuk Begalung/Cengkeh N...",https://gofood.co.id/en/restaurant/risol-mayo-...,a28ebd89-657f-4ce4-8760-bebd5503f057,NaN,1377,Pariaman,1377,Pariaman,NaN,NaN,"Snacks, Fast food, Noodles",4.3,NaN,NaN,2023-01-25T14:32:44.971Z,False,NaN,NaN,2026-04-14T09:19:03.684Z
1,gofood,"Mie Uda Bro, Lubuk Begalung",https://gofood.co.id/en/restaurant/mie-uda-bro...,4d0f26e1-dc90-47da-88c3-897191287d6a,NaN,1377,Pariaman,1377,Pariaman,NaN,NaN,"Rice, Snacks, Noodles",4.8,NaN,NaN,2018-03-09T07:31:42.514Z,False,NaN,NaN,2026-04-14T09:19:03.684Z
2,gofood,"Dapurbuna Sambalmercon, Padang - Solok Raya",https://gofood.co.id/en/restaurant/dapurbuna-s...,1d62fb77-6c59-43bb-946a-65a7ae3637f4,NaN,1377,Pariaman,1377,Pariaman,NaN,NaN,"Chicken & duck, Rice",4.8,NaN,NaN,2023-09-21T14:32:19.572Z,False,NaN,NaN,2026-04-14T09:19:03.684Z

============================================================
Shopee
============================================================
Shape: (1945, 20)

Columns:
['platform', 'merchantName', 'merchantUrl', 'merchantId', 'address', 'provinceCode', 'provinceName', 'regencyCode', 'regencyName', 'districtCode', 'districtName', 'category', 'rating', 'totalProducts', 'totalSold', 'joinDate', 'isOfficialStore', 'phone', 'description', 'scrapedAt']

Sample:

,platform,merchantName,merchantUrl,merchantId,address,provinceCode,provinceName,regencyCode,regencyName,districtCode,districtName,category,rating,totalProducts,totalSold,joinDate,isOfficialStore,phone,description,scrapedAt
0,shopee,Bead.One,https://shopee.co.id/shop/53466746,53466746,Kab. Padang Pariaman,1377,Pariaman,1306.0,PADANG PARIAMAN,NaN,NaN,NaN,0.0,1.0,NaN,8 tahun lalu,False,NaN,NaN,2026-04-15T01:08:04.110Z
1,shopee,"Amanda0407""",https://shopee.co.id/shop/1386767911,1386767911,Padang,1377,Pariaman,1371.0,PADANG,NaN,NaN,NaN,0.0,3.0,NaN,18 bulan lalu,False,NaN,NaN,2026-04-15T01:08:04.110Z
2,shopee,YaloraSuite,https://shopee.co.id/shop/1720965634,1720965634,Padang,1377,Pariaman,1371.0,PADANG,NaN,NaN,NaN,4.0,2.0,NaN,3 bulan lalu,False,NaN,NaN,2026-04-15T01:08:04.110Z

============================================================
Tokopedia
============================================================
Shape: (3134, 20)

Columns:
['platform', 'merchantName', 'merchantUrl', 'merchantId', 'address', 'provinceCode', 'provinceName', 'regencyCode', 'regencyName', 'districtCode', 'districtName', 'category', 'rating', 'totalProducts', 'totalSold', 'joinDate', 'isOfficialStore', 'phone', 'description', 'scrapedAt']

Sample:

,platform,merchantName,merchantUrl,merchantId,address,provinceCode,provinceName,regencyCode,regencyName,districtCode,districtName,category,rating,totalProducts,totalSold,joinDate,isOfficialStore,phone,description,scrapedAt
0,tokopedia,Harris Shop,https://www.tokopedia.com/harrishop,harrishop,Jakarta Barat,13,Sumatera Barat,1377,Pariaman,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,2026-04-14T07:44:31.079Z
1,tokopedia,Kenkaa shop,https://www.tokopedia.com/kenkaylee,kenkaylee,Jakarta Pusat,13,Sumatera Barat,1377,Pariaman,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,2026-04-14T07:44:31.079Z
2,tokopedia,DMC shop online,https://www.tokopedia.com/dmcshopol,dmcshopol,Tangerang,13,Sumatera Barat,1377,Pariaman,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,2026-04-14T07:44:31.079Z

============================================================
Semua Platform
============================================================
Shape: (5684, 20)

Columns:
['platform', 'merchantName', 'merchantUrl', 'merchantId', 'address', 'provinceCode', 'provinceName', 'regencyCode', 'regencyName', 'districtCode', 'districtName', 'category', 'rating', 'totalProducts', 'totalSold', 'joinDate', 'isOfficialStore', 'phone', 'description', 'scrapedAt']

Sample:

,platform,merchantName,merchantUrl,merchantId,address,provinceCode,provinceName,regencyCode,regencyName,districtCode,districtName,category,rating,totalProducts,totalSold,joinDate,isOfficialStore,phone,description,scrapedAt
0,blibli,Apotek Adi Pharma,https://www.blibli.com/merchant/apotek-adi-pharma,apotek-adi-pharma,Kab. Padang Pariaman,1377,Pariaman,1306.0,PADANG PARIAMAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,2026-04-14T09:59:33.827Z
1,blibli,Apotek Al-Fath,https://www.blibli.com/merchant/apotek-al-fath,apotek-al-fath,Kab. Padang Pariaman,1377,Pariaman,1306.0,PADANG PARIAMAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,2026-04-14T09:59:33.827Z
2,blibli,Apotek Ara Medica,https://www.blibli.com/merchant/apotek-ara-medica,apotek-ara-medica,Kab. Padang Pariaman,1377,Pariaman,1306.0,PADANG PARIAMAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,2026-04-14T09:59:33.828Z

In [6]:
def standardize_columns(df):
    df = df.copy()

    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
    )

    rename_map = {
        "merchantname": "merchant_name",
        "merchanturl": "merchant_url",
        "provincename": "province_name",
        "regencyname": "regency_name",
        "districtname": "district_name",
    }

    df.rename(columns=rename_map, inplace=True)

    return df

In [7]:
dfs = {
    sheet: standardize_columns(df)
    for sheet, df in dfs.items()
}

In [8]:
for sheet, df in dfs.items():

    print("=" * 50)
    print(sheet)
    print("=" * 50)

    print(df.columns.tolist())

==================================================
Blibli
==================================================
['platform', 'merchant_name', 'merchant_url', 'merchantid', 'address', 'provincecode', 'province_name', 'regencycode', 'regency_name', 'districtcode', 'district_name', 'category', 'rating', 'totalproducts', 'totalsold', 'joindate', 'isofficialstore', 'phone', 'description', 'scrapedat']
==================================================
GoFood
==================================================
['platform', 'merchant_name', 'merchant_url', 'merchantid', 'address', 'provincecode', 'province_name', 'regencycode', 'regency_name', 'districtcode', 'district_name', 'category', 'rating', 'totalproducts', 'totalsold', 'joindate', 'isofficialstore', 'phone', 'description', 'scrapedat']
==================================================
Shopee
==================================================
['platform', 'merchant_name', 'merchant_url', 'merchantid', 'address', 'provincecode', 'province_name', 'regencycode', 'regency_name', 'districtcode', 'district_name', 'category', 'rating', 'totalproducts', 'totalsold', 'joindate', 'isofficialstore', 'phone', 'description', 'scrapedat']
==================================================
Tokopedia
==================================================
['platform', 'merchant_name', 'merchant_url', 'merchantid', 'address', 'provincecode', 'province_name', 'regencycode', 'regency_name', 'districtcode', 'district_name', 'category', 'rating', 'totalproducts', 'totalsold', 'joindate', 'isofficialstore', 'phone', 'description', 'scrapedat']
==================================================
Semua Platform
==================================================
['platform', 'merchant_name', 'merchant_url', 'merchantid', 'address', 'provincecode', 'province_name', 'regencycode', 'regency_name', 'districtcode', 'district_name', 'category', 'rating', 'totalproducts', 'totalsold', 'joindate', 'isofficialstore', 'phone', 'description', 'scrapedat']

In [9]:
def normalize_text(text):

    if pd.isna(text):
        return ""

    text = str(text).lower()

    # remove non alphanumeric
    text = re.sub(r"[^a-z0-9\s]", " ", text)

    # remove multiple spaces
    text = re.sub(r"\s+", " ", text)

    return text.strip()

In [10]:
TEXT_COLUMNS = [
    "merchant_name",
    "address",
    "province_name",
    "regency_name",
    "district_name",
]

In [11]:
for sheet, df in dfs.items():

    for col in TEXT_COLUMNS:

        if col in df.columns:
            df[col] = df[col].apply(normalize_text)

    dfs[sheet] = df

In [12]:
for sheet, df in dfs.items():

    merchant = df.get("merchant_name", "")
    address = df.get("address", "")

    df["combined_text"] = (
        merchant.fillna("") + " " +
        address.fillna("")
    )

    df["combined_text"] = (
        df["combined_text"]
        .apply(normalize_text)
    )

    dfs[sheet] = df

In [13]:
for sheet, df in dfs.items():

    print("=" * 60)
    print(sheet)
    print("=" * 60)

    display(
        df[
            [
                "merchant_name",
                "address",
                "combined_text"
            ]
        ].head(5)
    )

============================================================
Blibli
============================================================

,merchant_name,address,combined_text
0,apotek adi pharma,kab padang pariaman,apotek adi pharma kab padang pariaman
1,apotek al fath,kab padang pariaman,apotek al fath kab padang pariaman
2,apotek ara medica,kab padang pariaman,apotek ara medica kab padang pariaman
3,apotek mulya farma,kab padang pariaman,apotek mulya farma kab padang pariaman

============================================================
GoFood
============================================================

,merchant_name,address,combined_text
0,risol mayo delicious lubuk begalung cengkeh na...,,risol mayo delicious lubuk begalung cengkeh na...
1,mie uda bro lubuk begalung,,mie uda bro lubuk begalung
2,dapurbuna sambalmercon padang solok raya,,dapurbuna sambalmercon padang solok raya
3,pecel ayam uda rimbo datar lubuk kilangan,,pecel ayam uda rimbo datar lubuk kilangan
4,station tahu sumedang jl raya indarung rimbo d...,,station tahu sumedang jl raya indarung rimbo d...

============================================================
Shopee
============================================================

     merchant_name              address                 combined_text
0         bead one  kab padang pariaman  bead one kab padang pariaman
1       amanda0407               padang             amanda0407 padang
2      yalorasuite               padang            yalorasuite padang
3  proleved padang               padang        proleved padang padang
4         afinaksr               padang               afinaksr padang

============================================================
Tokopedia
============================================================

         merchant_name            address                        combined_text
0          harris shop      jakarta barat            harris shop jakarta barat
1          kenkaa shop      jakarta pusat            kenkaa shop jakarta pusat
2      dmc shop online          tangerang            dmc shop online tangerang
3  bright shop lentera    jakarta selatan  bright shop lentera jakarta selatan
4       te oranga shop  tangerang selatan     te oranga shop tangerang selatan

============================================================
Semua Platform
============================================================

,merchant_name,address,combined_text
0,apotek adi pharma,kab padang pariaman,apotek adi pharma kab padang pariaman
1,apotek al fath,kab padang pariaman,apotek al fath kab padang pariaman
2,apotek ara medica,kab padang pariaman,apotek ara medica kab padang pariaman
3,apotek mulya farma,kab padang pariaman,apotek mulya farma kab padang pariaman
4,risol mayo delicious lubuk begalung cengkeh na...,,risol mayo delicious lubuk begalung cengkeh na...

In [14]:
REGION_COLUMNS = [
    "province_name",
    "regency_name",
    "district_name"
]

In [15]:
for sheet, df in dfs.items():

    print("\n")
    print("=" * 70)
    print(f"SHEET: {sheet}")
    print("=" * 70)

    for col in REGION_COLUMNS:

        if col in df.columns:

            print(f"\n--- {col.upper()} ---")

            print(
                df[col]
                .value_counts(dropna=False)
                .head(20)
            )

======================================================================
SHEET: Blibli
======================================================================

--- PROVINCE_NAME ---
province_name
pariaman    4
Name: count, dtype: int64

--- REGENCY_NAME ---
regency_name
padang pariaman    4
Name: count, dtype: int64

--- DISTRICT_NAME ---
district_name
    4
Name: count, dtype: int64


======================================================================
SHEET: GoFood
======================================================================

--- PROVINCE_NAME ---
province_name
pariaman    601
Name: count, dtype: int64

--- REGENCY_NAME ---
regency_name
pariaman    601
Name: count, dtype: int64

--- DISTRICT_NAME ---
district_name
    601
Name: count, dtype: int64


======================================================================
SHEET: Shopee
======================================================================

--- PROVINCE_NAME ---
province_name
pariaman            1507
pariaman selatan     438
Name: count, dtype: int64

--- REGENCY_NAME ---
regency_name
padang                      861
bukittinggi                 551
agam                         98
payakumbuh                   79
solok                        75
tanah datar                  49
padang pariaman              38
pariaman                     36
kab lima puluh koto kota     29
pesisir selatan              28
pasaman barat                27
padang panjang               24
sijunjung                    14
dharmasraya                  12
pasaman                      12
sawah lunto                   8
solok selatan                 4
Name: count, dtype: int64

--- DISTRICT_NAME ---
district_name
    1945
Name: count, dtype: int64


======================================================================
SHEET: Tokopedia
======================================================================

--- PROVINCE_NAME ---
province_name
sumatera barat    3134
Name: count, dtype: int64

--- REGENCY_NAME ---
regency_name
pariaman    3134
Name: count, dtype: int64

--- DISTRICT_NAME ---
district_name
    3134
Name: count, dtype: int64


======================================================================
SHEET: Semua Platform
======================================================================

--- PROVINCE_NAME ---
province_name
sumatera barat      3134
pariaman            2112
pariaman selatan     438
Name: count, dtype: int64

--- REGENCY_NAME ---
regency_name
pariaman                    3771
padang                       861
bukittinggi                  551
agam                          98
payakumbuh                    79
solok                         75
tanah datar                   49
padang pariaman               42
kab lima puluh koto kota      29
pesisir selatan               28
pasaman barat                 27
padang panjang                24
sijunjung                     14
dharmasraya                   12
pasaman                       12
sawah lunto                    8
solok selatan                  4
Name: count, dtype: int64

--- DISTRICT_NAME ---
district_name
    5684
Name: count, dtype: int64

In [16]:
VALID_KEYWORDS = [
    "pariaman",
    "kota pariaman",
]

INVALID_KEYWORDS = [
    "padang",
    "lubuk begalung",
    "bukittinggi",
    "solok",
    "payakumbuh",
    "agam",
    "jakarta",
    "bekasi",
    "depok",
    "tangerang",
]

In [17]:
def count_keyword_occurrences(df, keyword):

    return df["combined_text"].str.contains(
        keyword,
        case=False,
        na=False
    ).sum()

In [18]:
for keyword in VALID_KEYWORDS + INVALID_KEYWORDS:

    total = 0

    print("\n" + "=" * 50)
    print(f"KEYWORD: {keyword}")
    print("=" * 50)

    for sheet, df in dfs.items():

        count = count_keyword_occurrences(
            df,
            keyword
        )

        total += count

        print(f"{sheet:<20} {count}")

    print(f"\nTOTAL: {total}")

==================================================
KEYWORD: pariaman
==================================================
Blibli               4
GoFood               1
Shopee               74
Tokopedia            6
Semua Platform       85

TOTAL: 170

==================================================
KEYWORD: kota pariaman
==================================================
Blibli               0
GoFood               0
Shopee               0
Tokopedia            0
Semua Platform       0

TOTAL: 0

==================================================
KEYWORD: padang
==================================================
Blibli               4
GoFood               124
Shopee               924
Tokopedia            17

Semua Platform       1069

TOTAL: 2138

==================================================
KEYWORD: lubuk begalung
==================================================
Blibli               0
GoFood               23
Shopee               1
Tokopedia            0
Semua Platform       24

TOTAL: 48

==================================================
KEYWORD: bukittinggi
==================================================
Blibli               0
GoFood               0
Shopee               551
Tokopedia            26
Semua Platform       577

TOTAL: 1154

==================================================
KEYWORD: solok
==================================================
Blibli               0
GoFood               1
Shopee               79
Tokopedia            2
Semua Platform       82

TOTAL: 164

==================================================
KEYWORD: payakumbuh
==================================================
Blibli               0
GoFood               1
Shopee               79
Tokopedia            2
Semua Platform       82

TOTAL: 164

==================================================
KEYWORD: agam
==================================================
Blibli               0
GoFood               1
Shopee               100
Tokopedia            10
Semua Platform       111

TOTAL: 222

==================================================
KEYWORD: jakarta
==================================================
Blibli               0
GoFood               1
Shopee               0
Tokopedia            1043
Semua Platform       1044

TOTAL: 2088

==================================================
KEYWORD: bekasi
==================================================
Blibli               0
GoFood               0
Shopee               0
Tokopedia            239
Semua Platform       239

TOTAL: 478

==================================================
KEYWORD: depok
==================================================
Blibli               0
GoFood               0
Shopee               0
Tokopedia            123
Semua Platform       123

TOTAL: 246

==================================================
KEYWORD: tangerang
==================================================
Blibli               0
GoFood               0
Shopee               0
Tokopedia            441
Semua Platform       441

TOTAL: 882

In [19]:
TARGET_KEYWORD = "padang"

In [20]:
for sheet, df in dfs.items():

    matched = df[
        df["combined_text"]
        .str.contains(
            TARGET_KEYWORD,
            case=False,
            na=False
        )
    ]

    if len(matched) > 0:

        print("\n")
        print("=" * 70)
        print(sheet)
        print("=" * 70)

        display(
            matched[
                [
                    "merchant_name",
                    "address",
                    "combined_text"
                ]
            ].head(10)
        )

======================================================================
Blibli
======================================================================

,merchant_name,address,combined_text
0,apotek adi pharma,kab padang pariaman,apotek adi pharma kab padang pariaman
1,apotek al fath,kab padang pariaman,apotek al fath kab padang pariaman
2,apotek ara medica,kab padang pariaman,apotek ara medica kab padang pariaman
3,apotek mulya farma,kab padang pariaman,apotek mulya farma kab padang pariaman

======================================================================
GoFood
======================================================================

,merchant_name,address,combined_text
2,dapurbuna sambalmercon padang solok raya,,dapurbuna sambalmercon padang solok raya
5,chicken crush padang bandar buat,,chicken crush padang bandar buat
16,roti o jl raya bandar buat padang,,roti o jl raya bandar buat padang
29,ayam gebug padang,,ayam gebug padang
36,roti o rs semen padang,,roti o rs semen padang
45,oseng mercon padang pasar baru,,oseng mercon padang pasar baru
49,roti john by tom burger pasar baru unand kec p...,,roti john by tom burger pasar baru unand kec p...
52,esteh indonesia pasar baru padang,,esteh indonesia pasar baru padang
54,d besto pasar baru padang,,d besto pasar baru padang
57,bofet syntia martabak mesir jl raya padang,,bofet syntia martabak mesir jl raya padang

======================================================================
Shopee
======================================================================

        merchant_name              address                       combined_text
0            bead one  kab padang pariaman        bead one kab padang pariaman
1          amanda0407               padang                   amanda0407 padang
2         yalorasuite               padang                  yalorasuite padang
3     proleved padang               padang              proleved padang padang
4            afinaksr               padang                     afinaksr padang
7       elnoraleilani               padang                elnoraleilani padang
8          uni na bag               padang                   uni na bag padang
11  selly fashionshop               padang            selly fashionshop padang
16     rstore fashion  kab padang pariaman  rstore fashion kab padang pariaman
17  mallory tevy shop               padang            mallory tevy shop padang

======================================================================
Tokopedia
======================================================================

,merchant_name,address,combined_text
756,samudera bangunan abadi,padang,samudera bangunan abadi padang
1181,hn elektronik padang,padang,hn elektronik padang padang
1697,ima kedai beras,padang,ima kedai beras padang
1700,kedai omma padang lapai,padang,kedai omma padang lapai padang
1837,toko ananda tekstile,padang,toko ananda tekstile padang
1884,putra jaya tekstil,padang,putra jaya tekstil padang
1916,kamari tekstil,padang,kamari tekstil padang
2074,mama aisyah store sulaman,padang,mama aisyah store sulaman padang
2075,dila sulaman,kab padang pariaman,dila sulaman kab padang pariaman
2216,rina trophy bordir komputer,kab padang pariaman,rina trophy bordir komputer kab padang pariaman

======================================================================
Semua Platform
======================================================================

,merchant_name,address,combined_text
0,apotek adi pharma,kab padang pariaman,apotek adi pharma kab padang pariaman
1,apotek al fath,kab padang pariaman,apotek al fath kab padang pariaman
2,apotek ara medica,kab padang pariaman,apotek ara medica kab padang pariaman
3,apotek mulya farma,kab padang pariaman,apotek mulya farma kab padang pariaman
6,dapurbuna sambalmercon padang solok raya,,dapurbuna sambalmercon padang solok raya
9,chicken crush padang bandar buat,,chicken crush padang bandar buat
20,roti o jl raya bandar buat padang,,roti o jl raya bandar buat padang
33,ayam gebug padang,,ayam gebug padang
40,roti o rs semen padang,,roti o rs semen padang
49,oseng mercon padang pasar baru,,oseng mercon padang pasar baru

In [21]:
VALID_PHRASES = [
    "padang pariaman",
    "kab padang pariaman",
    "kota pariaman",
    "pariaman",
]

In [22]:
INVALID_PHRASES = [
    "kota padang",
    "lubuk begalung",
    "bandar buat",
    "pasar baru padang",
    "solok raya",
    "rs semen padang",
    "bukittinggi",
    "payakumbuh",
    "agam",
    "jakarta",
    "bekasi",
    "depok",
    "tangerang",
]

In [23]:
from collections import Counter

In [24]:
def extract_top_words(df, top_n=100):

    all_text = " ".join(
        df["combined_text"]
        .dropna()
        .astype(str)
        .tolist()
    )

    words = all_text.split()

    # filter kata terlalu pendek
    words = [
        word
        for word in words
        if len(word) > 3
    ]

    counter = Counter(words)

    return counter.most_common(top_n)

In [25]:
for sheet, df in dfs.items():

    print("\n")
    print("=" * 70)
    print(f"SHEET: {sheet}")
    print("=" * 70)

    top_words = extract_top_words(df)

    for word, count in top_words:
        print(f"{word:<25} {count}")

======================================================================
SHEET: Blibli
======================================================================
apotek                    4
padang                    4
pariaman                  4
pharma                    1
fath                      1
medica                    1
mulya                     1
farma                     1


======================================================================
SHEET: GoFood
======================================================================
padang                    127
ayam                      104
geprek                    36
lubuk                     30
baru                      30
kopi                      27
pecel                     26
nasi                      26
begalung                  25
hatta                     24
bakar                     24
kuranji                   23
raya                      22
goreng                    22
sutomo                    22
ampera                    21
pondok                    21
timur                     21
coffee                    20
pasar                     20
parak                     20
jati                      20
rumah                     19
lele                      18
simpang                   18
pauh                      18
andalas                   18
bandar                    17
roti                      17
ampang                    17
makan                     16
besto                     15
kebab                     14
soto                      13
bakso                     13
basko                     13
chicken                   12
padeh                     12
gadang                    12
sawahan                   12
sambal                    11
cabang                    11
warung                    11
perintis                  11
jalan                     10
kampung                   10
dapur                     10
depan                     10
ikan                      10
mall                      10
kemerdekaan               10
pangilun                  10
martabak                  9
cafe                      9
pisang                    9
unand                     9
dimsum                    9
pass                      8
sate                      8
burger                    8
pizza                     8
komplek                   8
city                      8
abdul                     8
muis                      8
barat                     8
yani                      8
buat                      7
bunda                     7
ruko                      7
bofet                     7
gadut                     7
gunung                    7
gulai                     7
donat                     7
laweh                     7
bypass                    7
balai                     7
proklamasi                7
thamrin                   7
ahmad                     7
purus                     7
indarung                  6
cemilan                   6
lubeg                     6
gepuk                     6
salad                     6
anduring                  6
kalawi                    6
mama                      6
haru                      6
bakmi                     6
niaga                     6
kitchen                   5
waroeng                   5
kubang                    5
john                      5
gembus                    5
cream                     5
lamongan                  5


======================================================================
SHEET: Shopee
======================================================================
shop                      1663
padang                    938
bukittinggi               554
agam                      99
payakumbuh                80
solok                     79
pariaman                  74
tanah                     49
datar                     49
pasaman                   39
selatan                   32
lima                      29
puluh                     29
koto                      29
kota                      29
pesisir                   28
sijunjung                 28
barat                     27
store                     26
panjang                   25
sawah                     22
lunto                     22
dharmasraya               12
apotek                    10
sumbar                    7
official                  7
snack                     6
toko                      5
baby                      4
grosir                    4
cemilan                   4
minang                    4
oleh                      4
farma                     4
fashion                   3
jeans                     3
center                    3
kids                      3
creative                  3
underwear                 3
rendang                   3
food                      3
sanjai                    3
kripik                    3
balado                    3
bead                      2
amanda0407                2
yalorasuite               2
proleved                  2
afinaksr                  2
anindy0705                2
monzazhafira              2
elnoraleilani             2
afninda                   2
apparels                  2
nizam                     2
store11                   2
store08                   2
linda                     2
zyana                     2
altan                     2
mahesasport               2
sultan                    2
sagalo                    2
lakubana100               2
malik                     2
smartphone                2
1435642446                2
435371351                 2
270248048                 2
285527809                 2
762158999                 2
166986110                 2
819327859                 2
1048938446                2
387513086                 2
56960789                  2
1533770795                2
1021462942                2
921573234                 2
399403510                 2
1696758432                2
1281550475                2
1130940                   2
326978183                 2
825476189                 2
914603610                 2
233489200                 2
199532465                 2
131160385                 2
299380366                 2
1054390584                2
1779029144                2
476112222                 2
733515268                 2
1354840056                2
1766690395                2
784342140                 2
113143660                 2
10496781                  2


======================================================================
SHEET: Tokopedia
======================================================================
jakarta                   1057
tangerang                 446
selatan                   346
barat                     296
toko                      277
bekasi                    249
pusat                     231
store                     209
timur                     191
utara                     166
grosir                    161
komputer                  153
elektronik                148
bangunan                  148
olshop                    145
bordir                    144
mart                      143
bogor                     142
fashion                   142
celluler                  142
cell                      141
minuman                   139
kedai                     138
warung                    134
depok                     133
bandung                   130
konter                    130
pakaian                   126
pasar                     107
tekstil                   96
jaya                      71
surabaya                  69
minimarket                57
shop                      49
makanan                   46
malang                    34
tasikmalaya               33
bukittinggi               29
sulaman                   29
apotek                    28
online                    27
sidoarjo                  27
cellular                  25
medan                     24
official                  23
semarang                  23
herbal                    22
murah                     22
obat                      22
lampung                   21
makassar                  20
kopi                      19
sleman                    19
aneka                     19
padang                    19
agen                      18
pekanbaru                 17
indonesia                 17
palembang                 17
cahaya                    15
pekalongan                15
garut                     15
denpasar                  14
bahan                     14
wanita                    14
anak                      13
sukoharjo                 13
kediri                    13
gudang                    13
sehat                     12
indo                      12
pasuruan                  12
bali                      12
nusantara                 12
cimahi                    12
sparepart                 12
baru                      11
cilacap                   11
bandar                    11
banjarmasin               11
bubuk                     11
pria                      11
yogyakarta                11
offical                   10
berkah                    10
serang                    10
kudus                     10
bantul                    10
sinar                     10
buku                      9
makmur                    9
bintang                   9
raja                      9
surakarta                 9
muslim                    9
jember                    9
cirebon                   9
jual                      9
aceh                      9
tekstile                  9


======================================================================
SHEET: Semua Platform
======================================================================
shop                      1712
padang                    1088
jakarta                   1058
bukittinggi               583
tangerang                 446
selatan                   383
barat                     331
toko                      286
bekasi                    249
store                     235
pusat                     232
timur                     212
utara                     168
grosir                    165
komputer                  154
elektronik                148
bangunan                  148
olshop                    147
mart                      146
warung                    145
kedai                     145
fashion                   145
bordir                    144
bogor                     142
celluler                  142
minuman                   141
cell                      141
bandung                   134
depok                     133
konter                    130
pasar                     127
pakaian                   126
agam                      108
ayam                      105
tekstil                   96
pariaman                  85
payakumbuh                84
solok                     82
jaya                      76
surabaya                  69
minimarket                57
datar                     52
tanah                     52
makanan                   48
kopi                      46
apotek                    42
baru                      41
pasaman                   40
geprek                    36
kota                      36
malang                    34
lubuk                     33
lima                      33
tasikmalaya               33
koto                      31
puluh                     30
official                  30
nasi                      29
online                    29
sulaman                   29
raya                      28
bandar                    28
pesisir                   28
sijunjung                 28
panjang                   27
sidoarjo                  27
begalung                  26
pecel                     26
rumah                     26
medan                     26
hatta                     25
cellular                  25
bakar                     24
murah                     24
kuranji                   23
jati                      23
sawah                     23
semarang                  23
goreng                    22
sutomo                    22
aneka                     22
lunto                     22
herbal                    22
obat                      22
coffee                    21
ampera                    21
indonesia                 21
pondok                    21
parak                     21
lampung                   21
makassar                  20
simpang                   19
andalas                   19
sleman                    19
lele                      18
roti                      18
pauh                      18
agen                      18
bakso                     17
ampang                    17

In [26]:
VALID_PHRASES = [
    "padang pariaman",
    "kab padang pariaman",
    "kota pariaman",
    "pariaman",
]

INVALID_PHRASES = [
    "lubuk begalung",
    "bandar buat",
    "kuranji",
    "ampang",
    "pauh",
    "parak",
    "andalas",
    "bukittinggi",
    "payakumbuh",
    "solok",
    "jakarta",
    "bekasi",
    "tangerang",
    "bogor",
    "bandung",
    "surabaya",
    "depok",
]

In [27]:
def classify_location(text):

    text = normalize_text(text)

    # PRIORITY 1
    for phrase in VALID_PHRASES:
        if phrase in text:
            return "KEEP"

    # PRIORITY 2
    for phrase in INVALID_PHRASES:
        if phrase in text:
            return "REJECT"

    # PRIORITY 3
    return "REVIEW"

In [28]:
for sheet, df in dfs.items():

    df["status"] = df["combined_text"].apply(
        classify_location
    )

    dfs[sheet] = df

In [29]:
for sheet, df in dfs.items():

    print("\n")
    print("=" * 70)
    print(sheet)
    print("=" * 70)

    print(
        df["status"]
        .value_counts()
    )

======================================================================
Blibli
======================================================================
status
KEEP    4
Name: count, dtype: int64


======================================================================
GoFood
======================================================================
status
REVIEW    471
REJECT    129
KEEP        1
Name: count, dtype: int64


======================================================================
Shopee
======================================================================
status
REVIEW    1161
REJECT     710
KEEP        74
Name: count, dtype: int64


======================================================================
Tokopedia
======================================================================
status
REJECT    2196
REVIEW     932
KEEP         6
Name: count, dtype: int64


======================================================================
Semua Platform
======================================================================
status
REJECT    3035
REVIEW    2564
KEEP        85
Name: count, dtype: int64

In [30]:
for sheet, df in dfs.items():

    review_df = df[
        df["status"] == "REVIEW"
    ]

    print("\n")
    print("=" * 70)
    print(sheet)
    print("=" * 70)

    print("TOTAL REVIEW:", len(review_df))

    display(
        review_df[
            [
                "merchant_name",
                "address",
                "combined_text"
            ]
        ].head(20)
    )

======================================================================
Blibli
======================================================================
TOTAL REVIEW: 0

Empty DataFrame
Columns: [merchant_name, address, combined_text]
Index: []

======================================================================
GoFood
======================================================================
TOTAL REVIEW: 471

,merchant_name,address,combined_text
3,pecel ayam uda rimbo datar lubuk kilangan,,pecel ayam uda rimbo datar lubuk kilangan
4,station tahu sumedang jl raya indarung rimbo d...,,station tahu sumedang jl raya indarung rimbo d...
6,pecel ayam pak abu jalan raya tanah sirah,,pecel ayam pak abu jalan raya tanah sirah
7,nasi uduk dan nasi goreng kim kitchen kampung ...,,nasi uduk dan nasi goreng kim kitchen kampung ...
9,dapur bunda crc,,dapur bunda crc
11,cultura coffee muhammad hatta,,cultura coffee muhammad hatta
12,ampera saiyo dr moh hatta,,ampera saiyo dr moh hatta
13,waroeng halim pecel lele hot tanjung sabar,,waroeng halim pecel lele hot tanjung sabar
14,ayam presto novi kampung dalam,,ayam presto novi kampung dalam
15,velocity pasar baru,,velocity pasar baru
17,zizi cemilan tanjung sabar,,zizi cemilan tanjung sabar
19,dua pintu coffee muhammad hatta,,dua pintu coffee muhammad hatta
20,boba kini ayam geprek cemilan lubuk kilangan,,boba kini ayam geprek cemilan lubuk kilangan
21,ayam geprek boba kini lubuk kilangan,,ayam geprek boba kini lubuk kilangan
23,mie adu nyali simpang piai,,mie adu nyali simpang piai
24,ampera mus by pass pisang,,ampera mus by pass pisang
26,rumah makan sederhana by pass,,rumah makan sederhana by pass
27,ruru coffee pasar baru,,ruru coffee pasar baru
28,pisang keju cricrulum m hatta,,pisang keju cricrulum m hatta
29,ayam gebug padang,,ayam gebug padang

======================================================================
Shopee
======================================================================
TOTAL REVIEW: 1161

              merchant_name          address                   combined_text
1                amanda0407           padang               amanda0407 padang
2               yalorasuite           padang              yalorasuite padang
3           proleved padang           padang          proleved padang padang
4                  afinaksr           padang                 afinaksr padang
6              monzazhafira         kab agam           monzazhafira kab agam
7             elnoraleilani           padang            elnoraleilani padang
8                uni na bag           padang               uni na bag padang
9          afninda apparels         kab agam       afninda apparels kab agam
10            meccaboutiqe2  kab dharmasraya   meccaboutiqe2 kab dharmasraya
11        selly fashionshop           padang        selly fashionshop padang
17        mallory tevy shop           padang        mallory tevy shop padang
18           alshad gallery           padang           alshad gallery padang
19     zaskiasungkar padang           padang     zaskiasungkar padang padang
20        vrizqashop padang           padang        vrizqashop padang padang
21                onya danu           padang                onya danu padang
24               momzka pdg           padang               momzka pdg padang
25              moccapurple           padang              moccapurple padang
27  elegant boutique padang           padang  elegant boutique padang padang
30                linda okt           padang                linda okt padang
31        zyana shop padang           padang        zyana shop padang padang

======================================================================
Tokopedia
======================================================================
TOTAL REVIEW: 932

,merchant_name,address,combined_text
393,raja olshop mlg,kab malang,raja olshop mlg kab malang
394,olshop stella new,kab sleman,olshop stella new kab sleman
400,olshoptidakmahal,kab karimun,olshoptidakmahal kab karimun
402,ika diesel olshop,medan,ika diesel olshop medan
403,anitaninoy olshop,kab cianjur,anitaninoy olshop kab cianjur
404,sneakers olshop mjk,kab mojokerto,sneakers olshop mjk kab mojokerto
414,rmt olshop,pekanbaru,rmt olshop pekanbaru
416,revalia olshop,surakarta,revalia olshop surakarta
417,789mart olshop solo,kab sukoharjo,789mart olshop solo kab sukoharjo
419,vino olshop 24,surakarta,vino olshop 24 surakarta
421,setara olshop,kab kediri,setara olshop kab kediri
427,berkat lancar olshop,kab mojokerto,berkat lancar olshop kab mojokerto
436,fendikpendik olshop,kab banyuwangi,fendikpendik olshop kab banyuwangi
441,porong taylor olshop,kab sidoarjo,porong taylor olshop kab sidoarjo
451,pbu olshop,kab serang,pbu olshop kab serang
460,ainun syakieb olshop,kab tegal,ainun syakieb olshop kab tegal
461,bagoong olshop,kab kudus,bagoong olshop kab kudus
462,pamotan olshop,kab rembang,pamotan olshop kab rembang
463,redick olshop,kab klaten,redick olshop kab klaten
472,cilacap olshop085728181878,kab cilacap,cilacap olshop085728181878 kab cilacap

======================================================================
Semua Platform
======================================================================
TOTAL REVIEW: 2564

,merchant_name,address,combined_text
7,pecel ayam uda rimbo datar lubuk kilangan,,pecel ayam uda rimbo datar lubuk kilangan
8,station tahu sumedang jl raya indarung rimbo d...,,station tahu sumedang jl raya indarung rimbo d...
10,pecel ayam pak abu jalan raya tanah sirah,,pecel ayam pak abu jalan raya tanah sirah
11,nasi uduk dan nasi goreng kim kitchen kampung ...,,nasi uduk dan nasi goreng kim kitchen kampung ...
13,dapur bunda crc,,dapur bunda crc
15,cultura coffee muhammad hatta,,cultura coffee muhammad hatta
16,ampera saiyo dr moh hatta,,ampera saiyo dr moh hatta
17,waroeng halim pecel lele hot tanjung sabar,,waroeng halim pecel lele hot tanjung sabar
18,ayam presto novi kampung dalam,,ayam presto novi kampung dalam
19,velocity pasar baru,,velocity pasar baru
21,zizi cemilan tanjung sabar,,zizi cemilan tanjung sabar
23,dua pintu coffee muhammad hatta,,dua pintu coffee muhammad hatta
24,boba kini ayam geprek cemilan lubuk kilangan,,boba kini ayam geprek cemilan lubuk kilangan
25,ayam geprek boba kini lubuk kilangan,,ayam geprek boba kini lubuk kilangan
27,mie adu nyali simpang piai,,mie adu nyali simpang piai
28,ampera mus by pass pisang,,ampera mus by pass pisang
30,rumah makan sederhana by pass,,rumah makan sederhana by pass
31,ruru coffee pasar baru,,ruru coffee pasar baru
32,pisang keju cricrulum m hatta,,pisang keju cricrulum m hatta
33,ayam gebug padang,,ayam gebug padang

In [31]:
for sheet, df in dfs.items():

    review_df = df[
        df["status"] == "REVIEW"
    ]

    print("\n")
    print("=" * 70)
    print(f"{sheet} - REVIEW WORDS")
    print("=" * 70)

    top_words = extract_top_words(
        review_df,
        top_n=100
    )

    for word, count in top_words:
        print(f"{word:<25} {count}")

======================================================================
Blibli - REVIEW WORDS
======================================================================


======================================================================
GoFood - REVIEW WORDS
======================================================================
padang                    112
ayam                      74
geprek                    28
baru                      26
hatta                     23
sutomo                    22
bakar                     20
ampera                    19
rumah                     19
kopi                      19
jati                      19
pecel                     18
nasi                      18
coffee                    18
timur                     18
goreng                    17
pasar                     17
pondok                    17
makan                     16
raya                      15
simpang                   15
lele                      13
besto                     12
basko                     12
sawahan                   12
roti                      11
perintis                  11
depan                     10
bakso                     10
cabang                    10
bandar                    10
kemerdekaan               10
pangilun                  10
kampung                   9
dapur                     9
sambal                    9
kebab                     9
warung                    9
chicken                   9
mall                      9
jalan                     8
pass                      8
padeh                     8
soto                      8
komplek                   8
dimsum                    8
abdul                     8
muis                      8
barat                     8
yani                      8
bunda                     7
pisang                    7
ruko                      7
pizza                     7
unand                     7
cafe                      7
ikan                      7
city                      7
proklamasi                7
thamrin                   7
ahmad                     7
purus                     7
lubuk                     6
indarung                  6
sate                      6
salad                     6
gulai                     6
donat                     6
gadut                     6
haru                      6
balai                     6
niaga                     6
waroeng                   5
cemilan                   5
bofet                     5
gepuk                     5
warkop                    5
indah                     5
kalawi                    5
lotek                     5
taruko                    5
mama                      5
syahrir                   5
wahidin                   5
selatan                   5
bakmi                     5
agus                      5
salim                     5
gunung                    5
dobi                      5
gajah                     5
mada                      5
kilangan                  4
kitchen                   4
mercon                    4
esteh                     4
indonesia                 4
martabak                  4
gembus                    4
toko                      4


======================================================================
Shopee - REVIEW WORDS
======================================================================
shop                      995
padang                    899
agam                      99
tanah                     49
datar                     49
pasaman                   39
lima                      29
puluh                     29
koto                      29
kota                      29
pesisir                   28
selatan                   28
sijunjung                 28
barat                     27
panjang                   25
sawah                     22
lunto                     22
store                     17
dharmasraya               12
apotek                    6
toko                      5
snack                     4
official                  4
creative                  3
cemilan                   3
kripik                    3
balado                    3
farma                     3
amanda0407                2
yalorasuite               2
proleved                  2
afinaksr                  2
monzazhafira              2
elnoraleilani             2
afninda                   2
apparels                  2
linda                     2
zyana                     2
mahesasport               2
smartphone                2
1048938446                2
387513086                 2
56960789                  2
921573234                 2
1696758432                2
1130940                   2
825476189                 2
914603610                 2
131160385                 2
299380366                 2
1779029144                2
476112222                 2
733515268                 2
1766690395                2
784342140                 2
159410276                 2
104537023                 2
363045921                 2
160607779                 2
31117419                  2
450421707                 2
34587401                  2
346608748                 2
1590149079                2
802945499                 2
6165136                   2
170381027                 2
298683021                 2
111242533                 2
1475709336                2
234662639                 2
306860186                 2
13866699                  2
465546534                 2
1582908018                2
188427324                 2
26515966                  2
1750049649                2
1161507228                2
343440500                 2
21080714                  2
134840304                 2
504561353                 2
278691266                 2
1780708903                2
1460986429                2
8605672                   2
678610604                 2
13222900                  2
1880894                   2
46292898                  2
982194986                 2
452506616                 2
171834780                 2
1785120208                2
1461525579                2
102189731                 2
1772963116                2
414063905                 2
978961269                 2


======================================================================
Tokopedia - REVIEW WORDS
======================================================================
konter                    100
bordir                    81
minuman                   80
celluler                  73
komputer                  54
tekstil                   53
pakaian                   51
cell                      51
bangunan                  50
toko                      49
minimarket                43
malang                    34
tasikmalaya               33
sidoarjo                  26
medan                     24
kedai                     24
jaya                      23
pasar                     23
elektronik                23
semarang                  22
grosir                    21
lampung                   21
makassar                  20
sleman                    19
warung                    19
olshop                    18
pekanbaru                 17
palembang                 17
store                     17
padang                    16
pekalongan                15
garut                     15
fashion                   15
denpasar                  14
mart                      14
sukoharjo                 13
kediri                    13
makanan                   13
pasuruan                  12
cimahi                    12
cilacap                   11
bandar                    11
banjarmasin               11
yogyakarta                11
serang                    10
kudus                     10
bali                      10
bantul                    10
murah                     10
sulaman                   10
surakarta                 9
jember                    9
online                    9
cirebon                   9
aceh                      9
batam                     8
gresik                    8
sukabumi                  8
balikpapan                8
aneka                     8
pusat                     8
sumedang                  8
agam                      8
cellular                  8
pulsa                     8
mojokerto                 7
tegal                     7
jepara                    7
karawang                  7
samarinda                 7
serbuk                    7
timur                     7
tekstile                  7
wanita                    7
cianjur                   6
demak                     6
pontianak                 6
lamongan                  6
manado                    6
herbal                    6
probolinggo               6
banyumas                  6
tengah                    6
magelang                  6
bojonegoro                6
serdang                   6
banyuwangi                5
klaten                    5
duta                      5
gudang                    5
indonesia                 5
gorontalo                 5
jambi                     5
agen                      5
jual                      5
gianyar                   5
wonogiri                  5
deli                      5
surya                     5
banda                     5


======================================================================
Semua Platform - REVIEW WORDS
======================================================================
padang                    1027
shop                      997
agam                      107
konter                    100
minuman                   81
bordir                    81
ayam                      74
celluler                  73
toko                      58
komputer                  55
tekstil                   53
datar                     52
tanah                     51
pakaian                   51
cell                      51
bangunan                  50
minimarket                43
pasar                     40
pasaman                   40
barat                     38
selatan                   34
store                     34
malang                    34
tasikmalaya               33
lima                      32
kota                      32
koto                      31
puluh                     30
geprek                    28
warung                    28
kedai                     28
pesisir                   28
sijunjung                 28
baru                      27
medan                     26
jaya                      26
sidoarjo                  26
timur                     25
panjang                   25
hatta                     24
rumah                     23
kopi                      23
sawah                     23
grosir                    23
elektronik                23
sutomo                    22
jati                      22
lunto                     22
semarang                  22
bandar                    21
lampung                   21
bakar                     20
makassar                  20
raya                      19
nasi                      19
ampera                    19
sleman                    19
pecel                     18
coffee                    18
olshop                    18
goreng                    17
pondok                    17
mart                      17
pekanbaru                 17
palembang                 17
simpang                   16
makan                     16
pekalongan                15
garut                     15
fashion                   15
makanan                   14
denpasar                  14
lele                      13
dharmasraya               13
sukoharjo                 13
kediri                    13
besto                     12
basko                     12
sawahan                   12
pasuruan                  12
cimahi                    12
roti                      11
kudus                     11
perintis                  11
cilacap                   11
banjarmasin               11
yogyakarta                11
dapur                     10
depan                     10
bakso                     10
cabang                    10
aceh                      10
kemerdekaan               10
pangilun                  10
apotek                    10
serang                    10
bali                      10
bantul                    10
murah                     10
sulaman                   10

In [32]:
INVALID_PHRASES = [

    # PADANG AREAS
    "lubuk begalung",
    "lubuk kilangan",
    "bandar buat",
    "kuranji",
    "ampang",
    "pauh",
    "parak",
    "andalas",
    "pangilun",
    "purus",
    "indarung",
    "kalawi",
    "gadut",
    "by pass",
    "pasar baru",
    "muhammad hatta",
    "m hatta",
    "simpang piai",

    # SUMBAR NON PARIAMAN
    "bukittinggi",
    "payakumbuh",
    "solok",
    "agam",
    "dharmasraya",
    "pasaman",
    "sijunjung",
    "sawah lunto",
    "tanah datar",
    "pesisir selatan",
    "lima puluh kota",

    # NATIONAL
    "jakarta",
    "bekasi",
    "tangerang",
    "bogor",
    "bandung",
    "surabaya",
    "depok",
    "malang",
    "tasikmalaya",
    "medan",
    "makassar",
    "lampung",
    "semarang",
    "palembang",
    "pekanbaru",
    "denpasar",
]

In [33]:
ADDITIONAL_INVALID = [

    # PADANG SIGNAL
    "sutomo",
    "pangilun",
    "anduring",
    "gadang",
    "ratulangi",
    "sawahan",
    "purus",
    "taruko",
    "indarung",
    "kalawi",

    # NATIONAL
    "sidoarjo",
    "sleman",
    "pasuruan",
    "cimahi",
    "banjarmasin",
    "balikpapan",
    "gresik",
    "sukabumi",
    "tegal",
    "pontianak",
]

In [34]:
def classify_location_v2(text):

    text = normalize_text(text)

    # PRIORITY 1 — VALID
    for phrase in VALID_PHRASES:

        if phrase in text:

            return pd.Series({
                "status": "KEEP",
                "matched_rule": phrase,
                "confidence_score": 100
            })

    # PRIORITY 2 — INVALID
    for phrase in INVALID_PHRASES:

        if phrase in text:

            return pd.Series({
                "status": "REJECT",
                "matched_rule": phrase,
                "confidence_score": -100
            })

    # PRIORITY 3 — REVIEW
    return pd.Series({
        "status": "REVIEW",
        "matched_rule": "none",
        "confidence_score": 0
    })

In [35]:
for sheet, df in dfs.items():

    # HAPUS kolom lama jika sudah ada
    cols_to_drop = [
        "status",
        "matched_rule",
        "confidence_score"
    ]

    existing_cols = [
        col for col in cols_to_drop
        if col in df.columns
    ]

    if existing_cols:
        df = df.drop(columns=existing_cols)

    # APPLY CLASSIFICATION
    classification_result = df[
        "combined_text"
    ].apply(classify_location_v2)

    # GABUNGKAN
    df = pd.concat(
        [df, classification_result],
        axis=1
    )

    dfs[sheet] = df

In [36]:
for sheet, df in dfs.items():

    print("\n")
    print("=" * 70)
    print(sheet)
    print("=" * 70)

    display(
        df[
            [
                "merchant_name",
                "combined_text",
                "status",
                "matched_rule",
                "confidence_score"
            ]
        ].head(10)
    )

======================================================================
Blibli
======================================================================

,merchant_name,combined_text,status,matched_rule,confidence_score
0,apotek adi pharma,apotek adi pharma kab padang pariaman,KEEP,padang pariaman,100
1,apotek al fath,apotek al fath kab padang pariaman,KEEP,padang pariaman,100
2,apotek ara medica,apotek ara medica kab padang pariaman,KEEP,padang pariaman,100
3,apotek mulya farma,apotek mulya farma kab padang pariaman,KEEP,padang pariaman,100

======================================================================
GoFood
======================================================================

,merchant_name,combined_text,status,matched_rule,confidence_score
0,risol mayo delicious lubuk begalung cengkeh na...,risol mayo delicious lubuk begalung cengkeh na...,REJECT,lubuk begalung,-100
1,mie uda bro lubuk begalung,mie uda bro lubuk begalung,REJECT,lubuk begalung,-100
2,dapurbuna sambalmercon padang solok raya,dapurbuna sambalmercon padang solok raya,REJECT,solok,-100
3,pecel ayam uda rimbo datar lubuk kilangan,pecel ayam uda rimbo datar lubuk kilangan,REJECT,lubuk kilangan,-100
4,station tahu sumedang jl raya indarung rimbo d...,station tahu sumedang jl raya indarung rimbo d...,REJECT,indarung,-100
5,chicken crush padang bandar buat,chicken crush padang bandar buat,REJECT,bandar buat,-100
6,pecel ayam pak abu jalan raya tanah sirah,pecel ayam pak abu jalan raya tanah sirah,REVIEW,none,0
7,nasi uduk dan nasi goreng kim kitchen kampung ...,nasi uduk dan nasi goreng kim kitchen kampung ...,REVIEW,none,0
8,soto berkah lubuk begalung,soto berkah lubuk begalung,REJECT,lubuk begalung,-100
9,dapur bunda crc,dapur bunda crc,REVIEW,none,0

======================================================================
Shopee
======================================================================

,merchant_name,combined_text,status,matched_rule,confidence_score
0,bead one,bead one kab padang pariaman,KEEP,padang pariaman,100
1,amanda0407,amanda0407 padang,REVIEW,none,0
2,yalorasuite,yalorasuite padang,REVIEW,none,0
3,proleved padang,proleved padang padang,REVIEW,none,0
4,afinaksr,afinaksr padang,REVIEW,none,0
5,anindy0705,anindy0705 payakumbuh,REJECT,payakumbuh,-100
6,monzazhafira,monzazhafira kab agam,REJECT,agam,-100
7,elnoraleilani,elnoraleilani padang,REVIEW,none,0
8,uni na bag,uni na bag padang,REVIEW,none,0
9,afninda apparels,afninda apparels kab agam,REJECT,agam,-100

======================================================================
Tokopedia
======================================================================

,merchant_name,combined_text,status,matched_rule,confidence_score
0,harris shop,harris shop jakarta barat,REJECT,jakarta,-100
1,kenkaa shop,kenkaa shop jakarta pusat,REJECT,jakarta,-100
2,dmc shop online,dmc shop online tangerang,REJECT,tangerang,-100
3,bright shop lentera,bright shop lentera jakarta selatan,REJECT,jakarta,-100
4,te oranga shop,te oranga shop tangerang selatan,REJECT,tangerang,-100
5,braket official shop,braket official shop jakarta timur,REJECT,jakarta,-100
6,reffvin erdiham kuluna shop,reffvin erdiham kuluna shop depok,REJECT,depok,-100
7,stephanie dj shop,stephanie dj shop jakarta utara,REJECT,jakarta,-100
8,lautan mutiara shop,lautan mutiara shop tangerang,REJECT,tangerang,-100
9,kampfer hobby shop,kampfer hobby shop depok,REJECT,depok,-100

======================================================================
Semua Platform
======================================================================

,merchant_name,combined_text,status,matched_rule,confidence_score
0,apotek adi pharma,apotek adi pharma kab padang pariaman,KEEP,padang pariaman,100
1,apotek al fath,apotek al fath kab padang pariaman,KEEP,padang pariaman,100
2,apotek ara medica,apotek ara medica kab padang pariaman,KEEP,padang pariaman,100
3,apotek mulya farma,apotek mulya farma kab padang pariaman,KEEP,padang pariaman,100
4,risol mayo delicious lubuk begalung cengkeh na...,risol mayo delicious lubuk begalung cengkeh na...,REJECT,lubuk begalung,-100
5,mie uda bro lubuk begalung,mie uda bro lubuk begalung,REJECT,lubuk begalung,-100
6,dapurbuna sambalmercon padang solok raya,dapurbuna sambalmercon padang solok raya,REJECT,solok,-100
7,pecel ayam uda rimbo datar lubuk kilangan,pecel ayam uda rimbo datar lubuk kilangan,REJECT,lubuk kilangan,-100
8,station tahu sumedang jl raya indarung rimbo d...,station tahu sumedang jl raya indarung rimbo d...,REJECT,indarung,-100
9,chicken crush padang bandar buat,chicken crush padang bandar buat,REJECT,bandar buat,-100

In [37]:
summary_rows = []

for sheet, df in dfs.items():

    counts = (
        df["status"]
        .value_counts()
        .to_dict()
    )

    summary_rows.append({
        "sheet": sheet,
        "total_rows": len(df),
        "keep": counts.get("KEEP", 0),
        "review": counts.get("REVIEW", 0),
        "reject": counts.get("REJECT", 0),
    })

summary_df = pd.DataFrame(summary_rows)

summary_df

            sheet  total_rows  keep  review  reject
0          Blibli           4     4       0       0
1          GoFood         601     1     398     202
2          Shopee        1945    74     913     958
3       Tokopedia        3134     6     722    2406
4  Semua Platform        5684    85    2033    3566

In [38]:
OUTPUT_PATH = "../outputs/cleaned_result.xlsx"

with pd.ExcelWriter(
    OUTPUT_PATH,
    engine="openpyxl"
) as writer:

    # SUMMARY
    summary_df.to_excel(
        writer,
        sheet_name="SUMMARY",
        index=False
    )

    # EXPORT PER SHEET
    for sheet, df in dfs.items():

        df.to_excel(
            writer,
            sheet_name=sheet[:31],
            index=False
        )

        # KEEP ONLY
        keep_df = df[
            df["status"] == "KEEP"
        ]

        keep_df.to_excel(
            writer,
            sheet_name=f"{sheet[:20]}_KEEP",
            index=False
        )

        # REVIEW ONLY
        review_df = df[
            df["status"] == "REVIEW"
        ]

        review_df.to_excel(
            writer,
            sheet_name=f"{sheet[:20]}_REVIEW",
            index=False
        )

        # REJECT ONLY
        reject_df = df[
            df["status"] == "REJECT"
        ]

        reject_df.to_excel(
            writer,
            sheet_name=f"{sheet[:20]}_REJECT",
            index=False
        )

print("Export selesai!")

Export selesai!